---
title: "Classification Trees"
output: html_notebook
---
## Libraries
```{r}
library(tidyr)
library(tidyverse)
library(dplyr)
library(party)
library(partykit)
library(ggparty)
library(rpart)
library(treeheatr)
library(pROC)
```
## Import other data
```{r}
env <- read.csv(file.path(dataPath,"KF50_samples_env.csv"))

```

## Arrange the data
Manually create a class column with the desired classification. Needs "resKR"
```{r}
data <- cbind(data.frame(class = NA), sub.coredata) %>%
  add_column(SampID = row.names(.)) %>%
  left_join(., env) %>%
  column_to_rownames(., var = "SampID")
  

# Set number of classes needed
n<-7

# Make reclassification table
reclassify <- data.frame(level=c(1,4,5,5,3,3,3),
                         class=c(3,18,38,39,8,11,10),
                         new_class=sprintf("KR%s",seq(1:n)))

# Reclassify
for(i in 1:n){
  data[getsamplesingrp(resKR,reclassify$level[i],reclassify$class[i]),"class"]<-as.character(reclassify$new_class[i])
}

table(data$class)
```


## Parameters
```{r}
predictors <- paste(colnames(data)[2:333], collapse="+") # careful with col numbers!

fmla <- as.formula(paste("class", predictors,sep="~"))
fmla
```
## OR Filter spp to show only >1
And add some env var
```{r}
main<-data %>%
  select_if(~max(.)>1)%>%
  add_column(SampID = row.names(.)) %>%
  left_join(., env) %>%
  column_to_rownames(., var = "SampID")

predictors <- paste(colnames(main)[-1], collapse="+") # careful with col numbers!

fmla <- as.formula(paste("class", predictors,sep="~"))
fmla
```




## Fit tree
```{r}
# Fit full tree
tree_full <- rpart(fmla,
                   data=data,
                   method="class",
                   control=rpart.control(xval = 10,
                                         minbucket = 2, cp = 0)
)

# Select pruning depth (complexity parameter)
cp.select <- function(big.tree) {
  min.x <- which.min(big.tree$cptable[, 4]) #column 4 is xerror
  for(i in 1:nrow(big.tree$cptable)) {
    if(big.tree$cptable[i, 4] < big.tree$cptable[min.x, 4] + big.tree$cptable[min.x, 5]) return(big.tree$cptable[i, 1]) 
  }
}

cp <-cp.select(tree_full)
cp <- 0.03

# Prune Tree
tree_full_pruned <- rpart(fmla,
                          data=data,
                          method="class",
                          control=rpart.control(xval = 10,
                                                minbucket = 2, cp = cp))

tree_full_pruned$variable.importance

```
## Calculate M-AUC
Calculate multiclass area under the curve
```{r}
predictions <- predict(tree_full_pruned,type = "class")

crosscheck <- predictions %>%
  as.character() %>%
  cbind(.,data$class) %>%
  data.frame() %>%
  rename("predicted" = ".", "observed" = "V2") %>%
  mutate_all(as.factor) %>%
  mutate_all(as.integer)

accuracy<-pROC::auc(multiclass.roc(observed~predicted,crosscheck))
accuracy
```

## Plot it
### As party
```{r}
# library(devtools)
# source_url("https://raw.githubusercontent.com/martin-borkovec/ggparty/martin/R/add_splitvar_breaks_index_new.R")
# 
ap_tree_full_pruned <- as.party(tree_full_pruned)
# 
# rounded_labels <- add_splitvar_breaks_index_new(party_object = ap_tree_full_pruned,
#                                                 plot_data = ggparty:::get_plot_data(ap_tree_full_pruned), 
#                                                 round_digits = 2)
# 
# 
# ggparty(ap_tree_full_pruned) +
#   geom_edge() +
#   geom_edge_label(mapping = aes(label = unlist(rounded_labels)),
#                   data = rounded_labels) +
#   geom_node_splitvar()+
#   geom_node_label(aes(label = class), ids = "terminal")
```
### As heat tree
```{r}
pdf(file.path(outPath,"CT_fjord_env.pdf"), width=20, height=10) #adjust width as necessary
par(cex=50)
heat_tree(ap_tree_full_pruned,label_map = levels(data$class)
          #, data_test = data[,which(grepl("KF50", colnames(data)))]
           , show = "tree-only"
           )
dev.off()
```
### As heat tree with heatmap
```{r}
pdf(file.path(outPath,"CT_fjord_env_heat.pdf"), width=20, height=40) #adjust width as necessary
par(cex=0.5)
heat_tree(ap_tree_full_pruned,label_map = levels(data$class)
          #, data_test = data[,which(grepl("KF50", colnames(data)))]
          , show = "heat-tree"
          , heat_rel_height =0.5
          )
dev.off()
```