---
title: "Prep input data, including species cleaning"
author: "GGM & RR"
date: "09/29/2021"
output: html_notebook
---

## Libraries
```{r}
library(twinspan)
library(tidyr)
library(dplyr)
```


## Make the matrix into wide format
```{r}
trimmedwide <- trimmed %>% select(-c(TotAbu_pseudocount,TotAbu_count,density_n_100m2_count,clean_taxonomy)) %>%
  mutate(new_name = gsub(" ","",new_name)) %>%
  mutate(new_name = gsub("\\.","",new_name)) %>%
  mutate(new_name = tolower(new_name)) %>%
  pivot_wider(names_from = new_name, values_from = density_n_100m2_pseudocount, values_fill = 0, values_fn = sum)

head(trimmedwide)
```
## Subset samples
### Import necessary data
```{r}
sample_info <- read.csv(file.path(dataPath,"sample_info.csv")) %>%
  mutate(area_m2 = SegLengthM * meanFoV_m)

refer <- read.csv(file.path(dataPath,"reference.csv"), sep ="|")
```

### examine distribution of surveyed area
```{r}
par(mfrow=c(2,2))
hist(sample_info$area_m2, main ="Surveyed area", xlab = "Area (m2)")
hist(sample_info$SegLengthM, main ="Surveyed distance", xlab = "Length (m)")
```

### set thresholds for data quality
```{r}
# thresholds for total surveyed area
#survarea_upper <- 1200
#survarea_lower <- 250

# alternative, set thresholds for survey length (maybe better)
length_lower <- 150
length_upper <- 400

# threshold for picture quality
# in English, Doc: "either unknown, or not more than half with no vision, or not more than one quarter with poor vision"
poorvis_thres <- 0.75
novis_thres <- 0.5

#table(ifelse(is.na(sample_info$ok_vision),1,
#                       ifelse(sample_info$poor_vision<poorvis_thres&sample_info$no_vision<novis_thres,1,0)))

#View(cbind(ifelse(is.na(sample_info$ok_vision),1,
#                       ifelse(sample_info$poor_vision<poorvis_thres&sample_info$no_vision<novis_thres,1,0)),
#     sample_info$ok_vision, sample_info$poor_vision, sample_info$no_vision))

filter1 <- sum(sample_info$SegLengthM>length_lower&sample_info$SegLengthM<length_upper)
filter2 <- length(which(ifelse(is.na(sample_info$ok_vision),1,
                       ifelse(sample_info$poor_vision<poorvis_thres&sample_info$no_vision<novis_thres,1,0))==1))
filter <- sum(
    rowSums(
  cbind((sample_info$SegLengthM>length_lower&sample_info$SegLengthM<length_upper),ifelse(is.na(sample_info$ok_vision),1,
                       ifelse(sample_info$poor_vision<poorvis_thres&sample_info$no_vision<novis_thres,1,0))))==2)

summary<-data.frame("length_filter_pass"=filter1/dim(sample_info)[1],
                    "picqual_filter_pass" =filter2/dim(sample_info)[1],
                    "both" = filter/dim(sample_info)[1])

summary
```

## Twinspan
```{r}
tw_1 <- trimmedwide %>%
  select(-SampID) %>%
  #subset()
  twinspan()
```

