---
title: "Prep input data, including species cleaning"
author: "GGM & RR"
date: "09/29/2021"
output: html_notebook
---

## Set paths
```{r}
# delphi_prosjekt_drive <- "U:" # which letter have you mapped this drive to?
# 
# dataPath <- file.path(delphi_prosjekt_drive,"Mareano/VIDEOLAB/VIDEO DATA/200m_scale_species_by_sample/Data_Delivery_2021")
# outPath <- file.path(dataPath,"outputs")
# codePath <- getwd()
```

## Libraries
```{r}
library(readxl)
library(dplyr)
```

## Read data
```{r}
spmatrix <- read.csv(file.path(dataPath,"species_densities.csv"), sep ="|")
```

## Edit species
### import edits file
```{r}
edits <- read_xlsx(file.path(dataPath,"Further editing of taxa for analyses.xlsx"))
edits <- mutate(edits, original_name = gsub("&",";",`Row Labels`))
head(edits)
```

### modify species according to the edits
```{r}
# transcode species
spmatrix <- spmatrix %>% mutate(new_name = edits$`Replace with`[match(spmatrix$clean_taxonomy,edits$original_name)])
idx <- which(is.na(spmatrix$new_name))
spmatrix$new_name[idx]<- as.character(spmatrix$clean_taxonomy[idx])

# remove species
editrem <- edits %>% subset(Delete == "x")
idx <- which(is.na(match(spmatrix$clean_taxonomy,editrem$original_name)))
#idx <- which(is.na(match(spmatrix$new_name,editrem$original_name))) #or this?

# trimmed matrix
trimmed <- spmatrix[idx,]
```

## Aditional changes to species list
```{r}
# replace Baltina sp with Halipteris

spmatrix <- spmatrix %>% mutate(new_name = gsub("Balticina sp.",
                                                  "Halipteris sp.",
                                                  new_name))

# -	Gracilechinusacutus is split from Gracilechinusacutus;juvenile should we keep split?

spmatrix <- spmatrix %>% mutate(new_name = gsub("Gracilechinusacutus",
                                                  "Gracilechinusacutus;juvenile",
                                                  new_name))


# -	Suspect tunicatatrunk and ascidiaceasolitarybig are the same (could leave split, Pål to decide?)
# -	Should we remove buccinidae?
# -	Should we remove paralithodescamtschaticus? (they migrate long distances so are not associated with any particular habitat)

```

## Result
```{r}
unique(data.frame(sort(trimmed$new_name)))
write.csv(trimmed,file.path(outPath,"species_densities_trimmed.csv"),row.names = FALSE)
```
```{r}
```
```{r}

```


```{r}
```
