---
title: "Explore Twinspan results"
author: "GGM & RR"
date: "10/11/2021"
output: 
  html_notebook:
    toc: yes
  
---
## Libraries
```{r}
library(rgdal)
```

## Derive classifications
```{r}
samples <- trimmedwide %>%
  filter(new_filter) %>%
  filter(sample_info$VL[match(SampID, sample_info$SampID)]%in%good) %>%
  select(SampID)

res <- data.frame(SampID = samples, level1 = NA, level2= NA, level3 = NA, level4 = NA, level5 = NA, level6 = NA)

for(i in 1:6){
  res[,i+1]<-cut(tw_1, level = i)
}

f = function(x) length(unique(x))
lapply(res, FUN = f)

```

## Write some point shapefiles
```{r}
result <- SpatialPointsDataFrame(coords = cbind(sample_info$x_coord[match(res$SampID,sample_info$SampID)],
                                                sample_info$y_coord[match(res$SampID,sample_info$SampID)]),
                                 proj4string = CRS("+init=epsg:32633"),
                                 data =  res)

writeOGR(result, dsn = file.path(outPath, "Spatial"), "twinspan_results", driver = "ESRI Shapefile", overwrite_layer = TRUE)
table(res$level6)
```


## Classification query
```{r}
level = 6
class = 73
classreport(trimmedwide, res, level, class)
```
## Species query
```{r}
sp = "lopheliapertusa"
spquery(trimmedwide, res, sp)
```

## Extract all samples in a single class
```{r}
level = 6
class = 73
extract <- res %>%
  filter(res[paste0("level",level)]==class) %>%
  select(SampID) %>%
  pull()

# make it into a filter
class_filter <- match(extract,trimmedwide$SampID)
```

## Subtwinspan
```{r}
tw_2 <- trimmedwide %>%
  filter(new_filter) %>%
  filter(sample_info$VL[match(SampID, sample_info$SampID)]%in%good) %>%
  filter(SampID%in%extract) %>%
  select(-SampID) %>%
  select(which(!is.na(colSums(.)))) %>%
  #mutate_all(sqrt)%>%
  twinspan(cutlevels = cutlevelsPaal)

```

