---
title: "Get spatial predictions"
output: html_notebook
---

## Libraries and needed R objects
```{r}
load("WORKSPACE_modeltraining.Rdata")
library(tidyvers)
library(party)
library(snow)
```

## Get predictor data
This can't be saved as an R object, so I have to import it again
```{r}
pred <- raster("pred.tif")
names(pred)<-names_pred
mask<-readOGR("tiny.shp")
crop_pred <- mask(crop(pred,mask),mask)
```

## Crop predictor stack to biotope polygon

## Predict
```{r}
## Predict using the raster package function:
# list of factor levels
f1 <- levels(v$landscape)
f <- list(f1)
names(f) <-c("landscape")

predfun <- function(m, d, ...) predict(m, newdata=d, ...)

model = cforest(fmlabest,
                data=v, 
                control = cforest_unbiased(ntree=1000,mtry = 3))

#pc <- raster::predict(pred, model, OOB=TRUE, factors=f, fun=predfun)

## same, in parallel
beginCluster()
pc <- clusterR(crop_pred, predict, args=list(model=model, OOB=TRUE, factors=f, fun=predfun, index=1))
endCluster()

```
