---
title: "Modeling"
output: html_notebook
---

## Libraries
```{r}
library(raster)
library(rgdal)
library(partykit)
library(party)

library(usdm)
library(vegan)
library(glmnet)
```

## Predictors
```{r}
pred
```

## Make the response into a spatial object
```{r}
resp = "3031"
resp_spat <- respdf %>%
  rownames_to_column(var = "SampID")%>%
  left_join(sample_info)%>%
  select(SampID, resp, x_coord, y_coord)
resp_spat <-  SpatialPointsDataFrame(coords = resp_spat[,c(3,4)],
                                      data = resp_spat,
                                      proj4string = CRS("+proj=utm +zone=33 +datum=WGS84 +units=m +no_defs"))
```

## Extract values
```{r}
e <- extract(pred, resp_spat)
v <- e %>% data.frame(cbind(resp_spat)) %>% mutate(landscape = factor(landscape))
str(v)
```
## Variable selection
I don't think this is very important right now - all I care about is spatial predictions - but oh well
```{r}
fmla <- as.formula(paste(paste0("X",resp,"~"), 
                         paste(colnames(v)[1:(which(colnames(v)=="X")-1)], collapse= "+"))) # all predictors
m0 <- cforest(fmla,
                      data=v, # all observations 
                      control = cforest_unbiased(ntree=1000,mtry = 3))

```
